name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Get GitHub App token
        id: app-token
        uses: grafana/shared-workflows/actions/create-github-app-token@34f27887c37cafe70d34af57dfc86b468a31b8c4 # create-github-app-token/v0.3.3
        with:
          github_app: hosted-grafana-release-trigger
      - uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0.0
        with:
          token: ${{ steps.app-token.outputs.token }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
